import { Link } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { FiCopy as CopyIcon } from "react-icons/fi";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [url, setUrl] = useState("");
  const [link, setLink] = useState<Link | null>(null);
  const create = trpc.useMutation("link.create", { onSuccess: setLink });

  const onCreate = () => {
    create.mutate({ url });
  };

  const onCopy = (slug: string) => {
    navigator.clipboard.writeText(`https://tincy.link/${slug}`);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen bg-gray-50">
        <div className="m-auto flex w-full max-w-sm flex-col">
          <h1 className="text-center text-xl font-semibold text-slate-700">tincy.link</h1>
          <div className="mt-2 flex w-full flex-col rounded p-4 shadow-lg bg-white">
            <input
              type="url"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              placeholder="https://example.com"
              className="h-10 rounded px-2"
            />
            <button
              className="mt-4 h-10 rounded bg-slate-700 text-white"
              onClick={onCreate}
            >
              Create a tincy link!
            </button>
          </div>
          {link && (
            <div
              className="mt-4 rounded bg-white shadow-lg p-4 relative cursor-pointer"
              onClick={() => onCopy(link.slug)}
            >
              <p className="text-sm">https://tincy.link/{link.slug}</p>
              <p className="text-xs text-gray-600">{link.url}</p>
              <CopyIcon className="absolute right-4 top-1/2 transform -translate-y-1/2" />
            </div>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
