import { Link } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [url, setUrl] = useState("");
  const [link, setLink] = useState<Link | null>(null);
  const create = trpc.useMutation("link.create", { onSuccess: setLink });

  const onCreate = () => {
    create.mutate({ url });
  };

  const onCopy = (slug: string) => {
    navigator.clipboard.writeText(`https://tincy.link${slug}`);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="">
          <input
            type="url"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            placeholder="https://example.com"
          />
          <button onClick={onCreate}>Create a tincy link!</button>
          {link && (
            <div onClick={() => onCopy(link.slug)}>
              <p>https://tincy.link/{link.slug}</p>
              <p>{link.url}</p>
            </div>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
